/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package now.work;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

import now.work.dtos.RecieveDetail;
import now.work.utils.io.OriginalCsv;

public class App {
    public static void main(String[] args) throws IOException {
        Path inputFilePath = Paths.get("data/input.csv");
        OriginalCsv.createCsvWithHeader(inputFilePath, RecieveDetail.class);
    }
}
